Update permissions on bin/deploy.js
KissKissBankBank/kitten-launcher pull request #6
Opened 2016-12-07 17:10 UTC by Ynote

2016-12-08 17:25 UTC, LanF3usT approved these changes

2016-12-09 12:11 UTC, sunny approved these changes

2016-12-09 12:11 UTC, sunny commented on CHANGELOG.md
> +- Update deploy script.
`Rename deploy script.` ?

2016-12-09 12:14 UTC, sunny commented
Du coup je remplacerais dans le README `npm run deploy` par `bin/deploy`, je retirerais le script `"deploy": "babel-node bin/deploy.js"` du `package.js` et j'ajouterais un `#!babel-node` en haut de fichier. Ça "devrait" marcher. Peut-être.

2016-12-09 12:16 UTC, sunny requested changes
(Tant qu'on a pas retiré le `.js` du package.json aussi cette PR casse le déploiement.)

[edit] Nevermind, c'est fixé.

2016-12-09 13:22 UTC, Ynote commented on CHANGELOG.md
> +- Update deploy script.
Du coup, c'est plutôt `update` vu que je le renomme et que je change la manière dont on va l'utiliser.

2016-12-09 13:34 UTC, sunny approved these changes

2016-12-09 16:34 UTC, merged